import time

from databend_py.errors import WarehouseTimeoutException


# retry in 550s for WarehouseTimeoutException
def retry(times, exceptions):
    """
    Retry Decorator
    Retries the wrapped function/method `times` times if the exceptions listed
    in ``exceptions`` are thrown
    :type times: Int
    :param exceptions: Lists of exceptions that trigger a retry attempt
    :type exceptions: Tuple of Exceptions
    """

    def decorator(func):
        def newfn(*args, **kwargs):
            attempt = 1
            while attempt <= times:
                try:
                    return func(*args, **kwargs)
                except exceptions:
                    print(
                        "Exception thrown when attempting to run %s, attempt "
                        "%d of %d" % (func, attempt, times)
                    )
                    time.sleep(attempt * 10)
                    attempt += 1
            return func(*args, **kwargs)

        return newfn

    return decorator


@retry(times=3, exceptions=WarehouseTimeoutException)
def foo1():
    print("Some code here ....")
    print("Oh no, we have exception")
    raise WarehouseTimeoutException("Some error")


if __name__ == "__main__":
    foo1()
